import { CAMPAIGN, COMPANION_QUESTS, HUNTS, EXPEDITIONS, availableMissions, regionProgress, trialMission, getMission, TRIAL_MODIFIERS } from '../data/campaign.js';
import { REGIONS } from '../data/regions.js';
import { HERO_BY_ID } from '../data/heroes.js';
import { nextStory, storyCount, levelForXP, currentBonds } from '../game/progression.js';
import { icon } from './icons.js';
import { esc, button, badge, panelHeader, clock, number, meter } from './util.js';

const STAGE_ICONS={fight:'sword',rescue:'crew',defend:'shield',escort:'sail',sabotage:'heavy',collect:'book',relay:'arcane',escape:'dodge',boss:'skull',choice:'crown',oath:'shards',anchors:'bond',trial:'storm',eleven:'crew'};
const atlasPoints=[[65,137],[177,68],[291,126],[405,60],[520,111]];
function atlas(profile,selected){
  const count=storyCount(profile);
  return `<svg class="world-atlas" viewBox="0 0 590 205" role="img" aria-label="The five kingdoms of Aetherra"><defs><radialGradient id="atlasglow"><stop stop-color="#b6a1ff" stop-opacity=".24"/><stop offset="1" stop-color="#b6a1ff" stop-opacity="0"/></radialGradient></defs><path d="M10 177Q112 50 200 124T390 113 577 59" class="atlas-wind"/><path d="M16 189Q100 68 193 139T413 123 581 79" class="atlas-wind"/><path d="M65 137Q121 89 177 68T291 126 405 60 520 111" class="atlas-route"/>${atlasPoints.map(([x,y],i)=>{const unlocked=count>=i*8,r=REGIONS[i],done=regionProgress(profile,i);return `<g class="atlas-island ${selected===i?'active':''} ${unlocked?'':'locked'}" data-act="region" data-region="${i}" style="--island:${r.color}"><circle cx="${x}" cy="${y}" r="56" fill="url(#atlasglow)" opacity="${selected===i?'1':'.2'}"/><path d="M${x-33} ${y+5}l15-22 22-5 25 17-9 19-20 19-18-9z"/><path class="island-ridges" d="M${x-33} ${y+5}l30 5 32-5 M${x-3} ${y+10}l3 23 M${x-18} ${y-17}l15 27 5-32"/><text x="${x}" y="${y+1}" class="atlas-glyph">${unlocked?r.glyph:'◇'}</text><text x="${x}" y="${y+54}" class="atlas-caption">${r.short.toUpperCase()}</text><text x="${x}" y="${y+68}" class="atlas-progress">${unlocked?`${done.done} / ${done.total}`:'UNCHARTED'}</text></g>`;}).join('')}<text x="555" y="18" class="atlas-compass">N ↑</text></svg>`;
}
export function boardPanel(ui,options={}){
  const a=ui.app,p=a.profile,count=storyCount(p),next=nextStory(p),available=availableMissions(p),availableIds=new Set(available.map(m=>m.id));
  const category=options.category||'story',region=Number.isInteger(options.region)?options.region:next?.region??4;
  options.region=region;const base=category==='story'?CAMPAIGN:category==='companion'?COMPANION_QUESTS:category==='hunt'?HUNTS:category==='expedition'?EXPEDITIONS:[];
  const missions=base.filter(m=>m.region===region),tier=Math.max(1,Math.min(p.trialTier,options.tier||p.trialTier));
  let selected=category==='trial'?trialMission(options.eleven?20:tier,!!options.eleven):getMission(options.selected);
  if(!selected||category!=='trial'&&!missions.includes(selected))selected=missions.find(m=>availableIds.has(m.id)&&!p.completed.includes(m.id))||missions.find(m=>availableIds.has(m.id))||missions[0];
  if(selected)options.selected=selected.id;
  const unlocked=selected&&(category==='trial'?(options.eleven?p.ended:count>=8):availableIds.has(selected.id));
  const requiresHero=selected?.hero&&!p.party.includes(selected.hero),r=REGIONS[region],bonds=currentBonds(p);
  const selectedMedal=p.medals[selected?.id];
  return {
    html:`<section class="panel board-panel">${panelHeader('THE WARDEN · NAVIGATION','Chart a course','Five kingdoms above a living storm. Choose the people who will face it with you.')}<div class="board-top"><div class="atlas-container">${atlas(p,region)}</div><div class="board-progress"><p class="eyebrow">THE SHATTERED OATH</p><strong>${count}<span> / 40</span></strong><p>story missions fulfilled</p>${meter(count/40,'gold')}<small>${p.completed.filter(id=>COMPANION_QUESTS.some(m=>m.id===id)).length} / 22 companion missions<br>${p.unlocked.length} / 11 anchors aboard</small>${p.ended?`<label class="crownfall-toggle"><input type="checkbox" data-board="crownfall" ${p.crownfall?'checked':''}>${icon('storm')} Crownfall mode</label>`:''}</div></div>
      <div class="board-tabs" role="tablist">${[['story','The main story'],['companion','Companion oaths'],['expedition','Expeditions'],['hunt','Crown echoes'],['trial','Storm Trials']].map(([id,title])=>`<button role="tab" aria-selected="${category===id}" class="${category===id?'selected':''}" data-act="category" data-category="${id}">${title}${id==='trial'&&count<8?icon('lock'):''}</button>`).join('')}</div>
      <div class="board-body"><aside class="mission-list"><div class="region-tabs">${REGIONS.map((r,i)=>`<button class="${region===i?'selected':''}" data-act="region" data-region="${i}" title="${r.name}">${r.glyph}<span>${r.short}</span></button>`).join('')}</div>${category==='trial'?`<div class="trial-selection"><p class="eyebrow">THE STORM’S INVITATION</p><h2>Storm Trials</h2><p>Increasingly dangerous formations. Mutating battlefield rules. A blessing between hard-won waves.</p><label>Trial tier<select data-board="tier">${Array.from({length:Math.min(p.trialTier,1001)},(_,i)=>`<option value="${i+1}" ${tier===i+1?'selected':''}>Tier ${String(i+1).padStart(2,'0')}${i+1<=p.bestTrial?' · conquered':''}</option>`).join('')}</select></label>${button('Challenge the storm','trial',{kind:!options.eleven?'selected':''})}${button('The Eleven','eleven',{kind:options.eleven?'selected':'',glyph:p.ended?'crew':'lock',disabled:!p.ended})}<p class="fine-print">${count<8?'Defeat the Thunder Colossus to unlock Storm Trials.':'The Eleven unlocks after the main story. Its Crown echoes use the same abilities as your heroes.'}</p></div>`:missions.map(m=>{const open=availableIds.has(m.id),done=p.completed.includes(m.id);return `<button class="mission-card ${m.id===selected?.id?'selected':''} ${open?'':'locked'}" data-act="mission" data-id="${m.id}"><span class="mission-symbol">${icon(done?'check':open?m.kind==='companion'?'bond':m.kind==='hunt'?'skull':m.kind==='expedition'?'sail':'crown':'lock')}</span><span><small>${m.kind==='story'?`CHAPTER ${String(m.index+1).padStart(2,'0')}`:m.kind==='companion'?`${HERO_BY_ID[m.hero].short.toUpperCase()} · OATH ${m.part}`:m.kind==='expedition'?'EXPEDITION · '+esc(m.feature):'CROWN ECHO'}</small><strong>${open?esc(m.title):'An uncharted oath'}</strong><em>${done?`${p.medals[m.id]?.rank||'Completed'} distinction`:open?`Recommended level ${m.level}`:m.hero&&!p.unlocked.includes(m.hero)?'Awaiting a new companion':`After ${m.unlockAt??m.index} story missions`}</em></span>${m.id===selected?.id?icon('arrow'):''}</button>`;}).join('')||'<div class="empty-state">No missions of this kind in this kingdom.</div>'}</aside>
      <article class="mission-detail" style="--region:${r.color}">${selected?`<p class="eyebrow">${unlocked?`${REGIONS[selected.region].name.toUpperCase()} · ${selected.kind==='trial'?'TRIAL':selected.kind.toUpperCase()}`:'BEYOND THE CHARTED SKY'}</p><h2>${unlocked?esc(selected.title):'A story still waiting'}</h2><p class="mission-brief">${unlocked?esc(selected.brief):'Follow the main story and welcome new companions to reveal this mission. Its details will remain here when the Warden is ready.'}</p>${unlocked?`<div class="mission-meta">${badge(`LEVEL ${selected.level}`)}${badge(`${selected.stages.length} ENCOUNTER${selected.stages.length===1?'':'S'}`)}${p.crownfall?badge('CROWNFALL','danger'):''}${selectedMedal?badge(`${selectedMedal.rank.toUpperCase()} · ${clock(selectedMedal.time)}`,'gold'):''}</div><ol class="mission-stage-list">${selected.stages.map(stage=>`<li>${icon(STAGE_ICONS[stage.type]||'crown')}<span><small>${stage.type==='relay'?'RUNE PUZZLE':stage.type.toUpperCase()}</small>${esc(stage.title)}</span></li>`).join('')}</ol>${selected.modifier?.description?`<div class="trial-modifier">${icon('storm')}<p><strong>${esc(selected.modifier.name)}</strong>${esc(selected.modifier.description)}</p></div>`:''}<div class="mission-reward"><span>${icon('arcane')} ${number(selected.reward)} Aether <small>first completion</small></span>${selected.hero?`<span>${icon('bond')} ${HERO_BY_ID[selected.hero].short}’s ${selected.part===2?'relationship attack':'personal oath'}</span>`:''}${selected.eleven?`<span>${icon('crown')} Shared Crown armor & awakened ultimates</span>`:''}</div>`:''}`:''}</article>
      <aside class="formation"><p class="eyebrow">YOUR THREE ANCHORS</p><h3>Stand together</h3><div class="formation-slots">${p.party.map((id,i)=>{const h=HERO_BY_ID[id];return `<button class="formation-card" data-act="formation" data-slot="${i}" data-id="${id}" style="--element:${h.color}"><img src="${a.renderer.portrait(id)}" alt="${esc(h.name)}"><span><small>ANCHOR ${i+1}</small><strong>${h.short}</strong><em>${h.role.replace('The ','')}</em></span>${icon(h.element)}</button>`;}).join('')}</div><div class="formation-bonds"><small>RELATIONSHIP ATTACK</small><p>${bonds.length?esc(bonds.map(b=>b.name).join(' · ')):'Repair a companion’s oath to awaken a combination attack.'}</p></div>${requiresHero?`<p class="required-hero">${HERO_BY_ID[selected.hero].short} must be in the party for this personal mission.</p>${button(`Bring ${HERO_BY_ID[selected.hero].short}`,'bring',{glyph:'crew'})}`:''}<div class="formation-launch">${button(selectedMedal?'Replay this oath':'Set sail','launch',{kind:'primary',glyph:'sail',disabled:!unlocked||requiresHero})}<small>${p.checkpoint?'Starting another mission replaces the active checkpoint. Manual saves are untouched.':'Progress is saved at every encounter boundary.'}</small></div></aside></div></section>`,
    actions:{close:()=>ui.close(),region:b=>{options.region=Number(b.dataset.region);options.selected=null;ui.render();},category:b=>{options.category=b.dataset.category;options.selected=null;options.eleven=false;if(options.category==='expedition'&&region>1)options.region=0;ui.render();},mission:b=>{options.selected=b.dataset.id;ui.render();},formation:b=>a.openPanel('roster',{hero:b.dataset.id,slot:Number(b.dataset.slot)}),bring:()=>{a.changeParty(2,selected.hero);ui.render();},launch:()=>a.requestMission(selected),trial:()=>{options.eleven=false;ui.render();},eleven:()=>{options.eleven=true;ui.render();}},
    change:node=>{if(node.dataset.board==='tier'){options.tier=Number(node.value);options.eleven=false;ui.render();}if(node.dataset.board==='crownfall'){a.setCrownfall(node.checked);ui.render();}},
  };
}
